name: Deploy

on:
  workflow_run: ["Java CI with Gradle"]
    branches: [ main ]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "webtech-projekt-plantast"
          heroku_email: "s0579813@htw-berlin.de"